//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinder_appl
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyJob_Tab1
    {
        public int Appl_id { get; set; }
        public int User_id { get; set; }
        public int C_id { get; set; }
        public int job_id { get; set; }
        public string Cv { get; set; }
        public System.DateTime appl_date { get; set; }
        public string appl_sts { get; set; }
    }
}
