//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinder_appl
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompReg_Tab
    {
        public int Cid { get; set; }
        public string Cname { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Websiteaddr { get; set; }
        public string Location { get; set; }
    }
}
